#Конфигурация mySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create


#Служебная информация и список сайтов для индексации
config:
  webinterfacelogin: admin
  webinterfacepassword: 12345
  prefix: search_
  agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  webinterface: /admin
  site:
    - url: http://localhost:8080/test
      name: Test
    - url: https://www.playback.ru
      name: Интернет магазин
    - url: https://dimonvideo.ru
      name: Все для мобильных устройств

#Логирование Hibernate
logging:
  level:
    org.hibernate.SQL: debug

